  services:
    php:
      volumes:
        - ~/.config/nvim-external/xdebug-config/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      #It is necessary for linux environment.
      extra_hosts:
        - "host.docker.internal:host-gateway"

    database:
      ports:
        - 3306:3306

